from enum import Enum


class GraphType(Enum):

    BOXPLOT_VENDOR_TRANSACTION_COUNTS = 0
    BOXPLOT_VENDOR_TRANSACTION_AVERAGE_BTC = 1
    BOXPLOT_VENDOR_TRANSACTION_MAX_BTC = 2
    BOXPLOT_VENDOR_TRANSACTION_SUM_BTC = 4

    HBAR_VENDOR_TRANSACTION_COUNTS = 5
    HBAR_VENDOR_TRANSACTION_AVERAGE_BTC = 6
    HBAR_VENDOR_TRANSACTION_MAX_BTC = 7
    HBAR_VENDOR_TRANSACTION_SUM_BTC = 8

    BOXPLOT_SHIP_FROM_TRANSACTION_COUNTS = 9
    BOXPLOT_SHIP_FROM_TRANSACTION_AVERAGE_BTC = 10
    BOXPLOT_SHIP_FROM_TRANSACTION_MAX_BTC = 11
    BOXPLOT_SHIP_FROM_TRANSACTION_SUM_BTC = 12

    HBAR_SHIP_FROM_TRANSACTION_COUNTS = 13
    HBAR_SHIP_FROM_TRANSACTION_AVERAGE_BTC = 14
    HBAR_SHIP_FROM_TRANSACTION_MAX_BTC = 15
    HBAR_SHIP_FROM_TRANSACTION_SUM_BTC = 16
