from enum import Enum


class GraphType(Enum):
    BOXPLOT_VENDOR_TRANSACTION_COUNTS = 0
    BOXPLOT_VENDOR_TRANSACTION_AVERAGE_BTC = 1
    BOXPLOT_VENDOR_TRANSACTION_MAX_BTC = 2
    HBAR_VENDOR_TRANSACTION_COUNTS = 3
    HBAR_VENDOR_TRANSACTION_AVERAGE_BTC = 4
    HBAR_VENDOR_TRANSACTION_MAX_BTC = 5
    BOXPLOT_SHIP_FROM_TRANSACTION_COUNTS = 6
    BOXPLOT_SHIP_FROM_TRANSACTION_AVERAGE_BTC = 7
    BOXPLOT_SHIP_FROM_TRANSACTION_MAX_BTC = 8
    HBAR_SHIP_FROM_TRANSACTION_COUNTS = 9
    HBAR_SHIP_FROM_TRANSACTION_AVERAGE_BTC = 10
    HBAR_SHIP_FROM_TRANSACTION_MAX_BTC = 11
